# Generated by Django 4.2 on 2023-04-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='smalldesk',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
