# Generated by Django 4.2 on 2023-04-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_post_smalldesk'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
