# Generated by Django 4.2 on 2023-05-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_remove_cart_course_cart_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
