# Generated by Django 4.1.7 on 2023-04-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='Phone',
            new_name='phone',
        ),
    ]
