# Generated by Django 4.1.7 on 2023-04-10 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_phone_phone_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='verify_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
