# Generated by Django 4.2 on 2023-04-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_myvipuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyvipUser',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
