# Generated by Django 4.2 on 2023-05-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_contact_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('p', 'publish'), ('d', 'draft')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
